version: "3"

services:
    web-react:
        image: react-ts-parcel:0.0.2
        ports:
            - "1234:1234"
        volumes:
            - /Users/tilekbekkadyrov/learn/React/my_apps/react-ts-parcel/src:/app/src/
